export const investors = [
  {
    id: "INV001",
    name: "Ahmed Sani",
    email: "ahmed@example.com",
    amountInvested: "$25,000",
    totalInvestment: 3,
    kycStatus: "Approved",
    dateJoined: "2025-06-20",
  },
  {
    id: "INV002",
    name: "Mary Johnson",
    email: "mary@example.com",
    amountInvested: "$5,000",
    totalInvestment: 3,
    kycStatus: "Pending",
    dateJoined: "2025-07-02",
  },
  {
    id: "INV003",
    name: "David Lee",
    email: "david@example.com",
    amountInvested: "$80,000",
    totalInvestment: 3,
    kycStatus: "Rejected",
    dateJoined: "2025-05-15",
  },
]

export const transactions = [
  {
    id: "TXN001",
    investor: "Ahmed Sani",
    email: "ahmed.sani@example.com",
    type: "Deposit",
    plan: "Basic Investment",
    amount: "$5,000",
    method: "Card",
    status: "Approved",
    goal: "Build long-term capital",
    date: "2025-10-01",
  },
  {
    id: "TXN002",
    investor: "Mary Johnson",
    email: "mary.johnson@example.com",
    type: "Withdrawal",
    plan: "Advanced Investment",
    amount: "$2,500",
    method: "Bank",
    status: "Pending",
    goal: "Fund personal business",
    date: "2025-10-05",
  },
  {
    id: "TXN003",
    investor: "David Lee",
    email: "david.lee@example.com",
    type: "Deposit",
    plan: "Premium Investment",
    amount: "$10,000",
    method: "Wallet",
    status: "Rejected",
    goal: "Portfolio diversification",
    date: "2025-10-09",
  },
  {
    id: "TXN004",
    investor: "Susan Brown",
    email: "susan.brown@example.com",
    type: "Withdrawal",
    plan: "Advanced Investment",
    amount: "$3,200",
    method: "Card",
    status: "Approved",
    goal: "Home renovation",
    date: "2025-09-28",
  },
  {
    id: "TXN005",
    investor: "Michael Smith",
    email: "michael.smith@example.com",
    type: "Deposit",
    plan: "Basic Investment",
    amount: "$7,500",
    method: "Wallet",
    status: "Pending",
    goal: "Future real estate project",
    date: "2025-09-15",
  },
  {
    id: "TXN006",
    investor: "Janet Cole",
    email: "janet.cole@example.com",
    type: "Withdrawal",
    plan: "Premium Investment",
    amount: "$4,000",
    method: "Bank",
    status: "Rejected",
    goal: "Tuition payment",
    date: "2025-09-10",
  },
  {
    id: "TXN007",
    investor: "John Doe",
    email: "john.doe@example.com",
    type: "Deposit",
    plan: "Advanced Investment",
    amount: "$12,000",
    method: "Card",
    status: "Approved",
    goal: "Expand portfolio",
    date: "2025-09-08",
  },
  {
    id: "TXN008",
    investor: "Rachel Green",
    email: "rachel.green@example.com",
    type: "Withdrawal",
    plan: "Basic Investment",
    amount: "$1,800",
    method: "Wallet",
    status: "Pending",
    goal: "Travel expenses",
    date: "2025-09-03",
  },
  {
    id: "TXN009",
    investor: "Paul Walker",
    email: "paul.walker@example.com",
    type: "Deposit",
    plan: "Premium Investment",
    amount: "$20,000",
    method: "Bank",
    status: "Approved",
    goal: "Generate passive income",
    date: "2025-08-28",
  },
  {
    id: "TXN010",
    investor: "Lisa Ray",
    email: "lisa.ray@example.com",
    type: "Withdrawal",
    plan: "Advanced Investment",
    amount: "$6,500",
    method: "Card",
    status: "Approved",
    goal: "Car purchase",
    date: "2025-08-20",
  },
];

export const kycSubmissions = [
  {
    id: 1,
    name: "Ahmed Sani",
    email: "ahmed@example.com",
    status: "Pending",
    submittedDate: "2025-10-12",
    documents: [
      { label: "ID Card", url: "/uploads/idcard_ahmed.png" },
      { label: "Proof of Address", url: "/uploads/address_ahmed.pdf" },
    ],
  },
  {
    id: 2,
    name: "Grace Johnson",
    email: "gracej@example.com",
    status: "Approved",
    submittedDate: "2025-10-09",
    documents: [
      { label: "Driver’s License", url: "/uploads/dl_grace.png" },
      { label: "Utility Bill", url: "/uploads/utility_grace.pdf" },
    ],
  },
  {
    id: 3,
    name: "Michael David",
    email: "mike@example.com",
    status: "Rejected",
    submittedDate: "2025-10-14",
    documents: [
      { label: "Passport", url: "/uploads/passport_mike.png" },
    ],
  },
];

